name: saveflow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  uuid: ^4.3.3
  google_fonts: ^6.1.0
  gap: ^3.0.1
  path_provider: ^2.1.2
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: 2.4.0
  hive_generator: ^2.0.1
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#00796B"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.png"
  branding: "assets/logo.png"
  color_dark: "#121212"
  image_dark: "assets/logo.png"

  android_12:
    image: "assets/logo.png"
    color: "#FFFFFF"
    icon_background_color: "#FFFFFF"
  
  web: false
